#!/usr/bin/env node

const cli = require('./lib/cli');

async function main() {
  try {
    await cli().start();
  }
  catch(e) {
    console.error(e.message);
    process.exitCode = 1;
  }
}

main();
